type Place {
  _id: ID!
  title: String!
  address: String!
  lat: Float!
  lng: Float!
}

input PlaceInput {
  title: String!
  address: String!
  lat: Float!
  lng: Float!
}

type Query {
  place(id: String!): Place
  places: [Place]!
}

type Mutation {
  newPlace(input: PlaceInput!): Place!
}
